# -*- coding: utf-8 -*-
"""00_HelloWord.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fvey2JM3WtOwcee5RKikZ3U2E4bhTzZ8
"""

#Este símbolo se utiliza para comentar el código.
print("Hola grupo 230 de la carrera técnica de programación")
# Como consultar el tipo de dato
print( type("soy un dato str")) #Tipo 'str'
print(type(5)) # Tipo 'int'
print(type(1.5)) # Tipo 'float'
print(type(3+1j)) # Tipo 'complex'
prin(type(True)) # Tipo bool